[cmd_duration]
min_time = 1000
format = "[$duration]($style)"
style = "yellow"

[git_branch]
format = "[$branch]($style) "
style = "242"

[git_status]
modified = "[*](218)"
stashed = "[â‰¡](cyan)"
ahead = "[â‡¡](cyan)"
diverged = "[â‡¡â‡£](cyan)"
behind = "[â‡£](cyan)"
format = '([$modified $ahead_behind]($style) )'

[directory]
truncate_to_repo = false
truncation_length = 0
read_only = " ğŸ”’"
style = "blue"

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"

[username]
style_user = "242"
format = "[$user]($style) @ "

[hostname]
style = "242"
format = "[$hostname]($style) "

[package]
disabled = true

[battery]
disabled = true

[python]
disabled = true

[java]
disabled = true

[swift]
disabled = true

[golang]
disabled = true

[kotlin]
disabled = true

[dart]
disabled = true

[conda]
disabled = true

[docker_context]
disabled = true

[nodejs]
disabled = true

[cmake]
disabled = true

[lua]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true
